export const barriosCABA = [
  { barrio: "Todos", id: -1 },
  { barrio: "Agronomía", id: 0 },
  { barrio: "Almagro", id: 1 },
  { barrio: "Balvanera", id: 2 },
  { barrio: "Barracas", id: 3 },
  { barrio: "Belgrano", id: 4 },
  { barrio: "Boedo", id: 5 },
  { barrio: "Caballito", id: 6 },
  { barrio: "Chacarita", id: 7 },
  { barrio: "Coghlan", id: 8 },
  { barrio: "Colegiales", id: 9 },
  { barrio: "Constitución", id: 10 },
  { barrio: "Flores", id: 11 },
  { barrio: "Floresta", id: 12 },
  { barrio: "La Boca", id: 13 },
  { barrio: "La Paternal", id: 14 },
  { barrio: "Liniers", id: 15 },
  { barrio: "Mataderos", id: 16 },
  { barrio: "Monte Castro", id: 17 },
  { barrio: "Monserrat", id: 18 },
  { barrio: "Nueva Pompeya", id: 19 },
  { barrio: "Núñez", id: 20 },
  { barrio: "Palermo", id: 21 },
  { barrio: "Parque Avellaneda", id: 22 },
  { barrio: "Parque Chacabuco", id: 23 },
  { barrio: "Parque Chas", id: 24 },
  { barrio: "Parque Patricios", id: 25 },
  { barrio: "Puerto Madero", id: 26 },
  { barrio: "Recoleta", id: 27 },
  { barrio: "Retiro", id: 28 },
  { barrio: "Saavedra", id: 29 },
  { barrio: "San Cristóbal", id: 30 },
  { barrio: "San Nicolás", id: 31 },
  { barrio: "San Telmo", id: 32 },
  { barrio: "Vélez Sársfield", id: 33 },
  { barrio: "Versalles", id: 34 },
  { barrio: "Villa Crespo", id: 35 },
  { barrio: "Villa del Parque", id: 36 },
  { barrio: "Villa Devoto", id: 37 },
  { barrio: "Villa General Mitre", id: 38 },
  { barrio: "Villa Lugano", id: 39 },
  { barrio: "Villa Luro", id: 40 },
  { barrio: "Villa Ortúzar", id: 41 },
  { barrio: "Villa Pueyrredón", id: 42 },
  { barrio: "Villa Real", id: 43 },
  { barrio: "Villa Riachuelo", id: 44 },
  { barrio: "Villa Santa Rita", id: 45 },
  { barrio: "Villa Soldati", id: 46 },
  { barrio: "Villa Urquiza", id: 47 },
];
